name: 'codewatchers-assignees'
description: 'Set PR assignees based on a CODEOWNERS file'
author: 'dovetail'
branding: 
  icon: 'users'
  color: 'blue'
inputs:
  github-token:
    required: true
    description: 'Auth token with permissions to label PR '
  codewatchers-filename:
    required: false
    description: 'Filename of codewatchers file.'
    default: 'CODEWATCHERS'
  github-user-mappings:
    required: false
    description: 'Optional list of mappings from codewatchers to github users. Delimited by colon.'
runs:
  using: 'node16'
  main: 'dist/index.js'
